package than.MK.weblaptop.backend.entity;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * AdministrativeRegions generated by hbm2java
 */
@Data
@Entity
@Table(name = "administrative_regions", catalog = "web_selling_laptop")
public class AdministrativeRegions implements java.io.Serializable {

    private int id;
    private String name;
    private String nameEn;
    private String codeName;
    private String codeNameEn;

    public AdministrativeRegions() {
    }

    public AdministrativeRegions(int id, String name, String nameEn) {
        this.id = id;
        this.name = name;
        this.nameEn = nameEn;
    }

    public AdministrativeRegions(int id, String name, String nameEn, String codeName, String codeNameEn) {
        this.id = id;
        this.name = name;
        this.nameEn = nameEn;
        this.codeName = codeName;
        this.codeNameEn = codeNameEn;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "name_en", nullable = false)
    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    @Column(name = "code_name")
    public String getCodeName() {
        return this.codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    @Column(name = "code_name_en")
    public String getCodeNameEn() {
        return this.codeNameEn;
    }

    public void setCodeNameEn(String codeNameEn) {
        this.codeNameEn = codeNameEn;
    }

}
