package than.MK.weblaptop.backend.entity;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * AdministrativeUnits generated by hbm2java
 */
@Data
@Entity
@Table(name = "administrative_units", catalog = "web_selling_laptop")
public class AdministrativeUnits implements java.io.Serializable {

    private int id;
    private String fullName;
    private String fullNameEn;
    private String shortName;
    private String shortNameEn;
    private String codeName;
    private String codeNameEn;

    public AdministrativeUnits() {
    }

    public AdministrativeUnits(int id) {
        this.id = id;
    }

    public AdministrativeUnits(int id, String fullName, String fullNameEn, String shortName, String shortNameEn,
                               String codeName, String codeNameEn) {
        this.id = id;
        this.fullName = fullName;
        this.fullNameEn = fullNameEn;
        this.shortName = shortName;
        this.shortNameEn = shortNameEn;
        this.codeName = codeName;
        this.codeNameEn = codeNameEn;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "full_name")
    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Column(name = "full_name_en")
    public String getFullNameEn() {
        return this.fullNameEn;
    }

    public void setFullNameEn(String fullNameEn) {
        this.fullNameEn = fullNameEn;
    }

    @Column(name = "short_name")
    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @Column(name = "short_name_en")
    public String getShortNameEn() {
        return this.shortNameEn;
    }

    public void setShortNameEn(String shortNameEn) {
        this.shortNameEn = shortNameEn;
    }

    @Column(name = "code_name")
    public String getCodeName() {
        return this.codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    @Column(name = "code_name_en")
    public String getCodeNameEn() {
        return this.codeNameEn;
    }

    public void setCodeNameEn(String codeNameEn) {
        this.codeNameEn = codeNameEn;
    }

}

