package than.MK.weblaptop.backend.entity;


// Generated Mar 19, 2024, 3:29:20 PM by Hibernate Tools 4.3.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Provinces generated by hbm2java
 */
@Data
@Entity
@Table(name = "provinces", catalog = "web_selling_laptop")
public class Provinces implements java.io.Serializable {

    private String code;
    private String name;
    private String nameEn;
    private String fullName;
    private String fullNameEn;
    private String codeName;
    private Integer administrativeUnitId;
    private Integer administrativeRegionId;

    public Provinces() {
    }

    public Provinces(String code, String name, String fullName) {
        this.code = code;
        this.name = name;
        this.fullName = fullName;
    }

    public Provinces(String code, String name, String nameEn, String fullName, String fullNameEn, String codeName,
                     Integer administrativeUnitId, Integer administrativeRegionId) {
        this.code = code;
        this.name = name;
        this.nameEn = nameEn;
        this.fullName = fullName;
        this.fullNameEn = fullNameEn;
        this.codeName = codeName;
        this.administrativeUnitId = administrativeUnitId;
        this.administrativeRegionId = administrativeRegionId;
    }

    @Id

    @Column(name = "code", unique = true, nullable = false, length = 20)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "name_en")
    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    @Column(name = "full_name", nullable = false)
    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Column(name = "full_name_en")
    public String getFullNameEn() {
        return this.fullNameEn;
    }

    public void setFullNameEn(String fullNameEn) {
        this.fullNameEn = fullNameEn;
    }

    @Column(name = "code_name")
    public String getCodeName() {
        return this.codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    @Column(name = "administrative_unit_id")
    public Integer getAdministrativeUnitId() {
        return this.administrativeUnitId;
    }

    public void setAdministrativeUnitId(Integer administrativeUnitId) {
        this.administrativeUnitId = administrativeUnitId;
    }

    @Column(name = "administrative_region_id")
    public Integer getAdministrativeRegionId() {
        return this.administrativeRegionId;
    }

    public void setAdministrativeRegionId(Integer administrativeRegionId) {
        this.administrativeRegionId = administrativeRegionId;
    }

}

